In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-price-dataset/Participants_Data_HPP/sample_submission.csv
/kaggle/input/house-price-dataset/Participants_Data_HPP/Train.csv
/kaggle/input/house-price-dataset/Participants_Data_HPP/Test.csv

In [2]:
df= pd.read_csv("/kaggle/input/house-price-dataset/Participants_Data_HPP/Train.csv")

In [3]:
#EXPLORATORY DATA ANALYSIS

In [4]:
df.shape

(29451, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  object
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  object
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  object
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB

In [6]:
df.head(5)

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [7]:
df.drop(['POSTED_BY','UNDER_CONSTRUCTION','RERA'], axis=1, inplace= True)
df.drop(['BHK_NO.','BHK_OR_RK','READY_TO_MOVE','RESALE'], axis=1, inplace= True)
df.drop(['ADDRESS','LONGITUDE','LATITUDE'], axis=1, inplace= True)

In [8]:
df.head(5)

     SQUARE_FT  TARGET(PRICE_IN_LACS)
0  1300.236407                   55.0
1  1275.000000                   51.0
2   933.159722                   43.0
3   929.921143                   62.5
4   999.009247                   60.5

In [9]:
df.isnull().sum()

SQUARE_FT                0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [10]:
y = df['TARGET(PRICE_IN_LACS)']
x = df.drop('TARGET(PRICE_IN_LACS)', axis=1)

In [11]:
#MODEL DEVELOPMENT

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state = 42)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [14]:
#MODEL1- RANDOM FOREST

In [15]:
regressor = RandomForestRegressor()  
regressor.fit(x_train, y_train)  
y_pred = regressor.predict(x_test)

In [16]:
#MODEL EVALUATION- MODEL1

In [17]:
from sklearn.metrics import mean_squared_error, mean_squared_error,r2_score
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)

print("mean squared error:", mse)
print("root mean squared error:", rmse)
print("r2 score:", r2)

mean squared error: 145638.01821794032
root mean squared error: 381.62549471692836
r2 score: 0.6887310443103508

In [18]:
#MODEL2- LINEAR-REGRESSOR

In [19]:
regressor_2= LinearRegression()
regressor_2.fit(x_train, y_train)
y_pred_2= regressor_2.predict(x_test)

In [20]:
#MODEL EVALUATION- MODEL2

In [21]:

mse = mean_squared_error(y_test, y_pred_2)
rmse = mean_squared_error(y_test, y_pred_2, squared=False)
r2 = r2_score(y_test, y_pred_2)

print("mean squared error:", mse)
print("root mean squared error:", rmse)
print("r2 score:", r2)

mean squared error: 334413.1564308142
root mean squared error: 578.2846672970105
r2 score: 0.28526606414453215